# Evaluación de la Vulnerabilidad Social

_________

Herramienta para la evaluación de la vulnerabilidad socioeconomica en zonas urbanas.

Con el fin de evaluar la vulnerabilidad socioeconomica se utiliza los censos de población del 2010 o 2020 realizados por el INEGI. La información esta separada en las tablas donde se describe factores socioeconómicos y la información vectorial que contiene en donde se levantaron dichos datos. 

El censo trata de recabar las principales características de la población y conocer su distribución en el territorio nacional, los censos en México se realzan cada 10 años, tiene características que lo hacen compatible con censos en otros países. El Censo 2020 aumenta el número de preguntas y pasa de 29 en 2010 en el Cuestionario Básico a 38 y de 75 a 103 en el Ampliado.

El siguiente enlace contiene una descripción detallada del [censo de población](https://www.inegi.org.mx/contenidos/productos/prod_serv/contenidos/espanol/bvinegi/productos/nueva_estruc/702825197520.pdf).

_________

## Base de datos

La base de datos en formato de tabla se puede descargar de la siguiente página [INEGI datos abiertos](https://www.inegi.org.mx/datosabiertos/).

Se puede obtener la información del censo de población 2010 y 2020. La herramienta utiliza los resultados por AGEB y manzana urbana.

> [!IMPORTANT]  
> Se observa que la información del censo de población 2010 solo se puede trabajar a nivel AGEB, debido que no contiene la información a nivel manzana, en cambio la información del censo 2020 si contiene información a nivel AGEB y manzana urbana.

> [!NOTE]
>
> **El antecedente de la herramienta fue diseñada por Katia Michelle Villarnobo, en donde en su tesis "[Subsidencia en municipios del Bajío (2014-2020) y una estimación de su riesgo ](http://132.248.9.195/ptd2022/noviembre/0832755/Index.html)", describe el proceso que realizó, comparte sus herramientas en su [Github](https://github.com/katiami/Subsidencia_Bajio_2014_2020/tree/main).**

_______________

## Información Geográfica

Para este análisis de vulnerabilidad, usaremos información espacial que esta relacionada con la información de la base de datos anterior, dependiendo del censo se tiene que relacionar con la información correspondiente:

Para el censo 2020 se utiliza el [Marco Geoestadístico. Censo de Población y Vivienda 2020](https://www.inegi.org.mx/app/biblioteca/ficha.html?upc=889463807469).

Para el censo 2010 se usa el [Marco Geoestadístico. Censo de Población y Vivienda 2010 version 5A](https://www.inegi.org.mx/app/biblioteca/ficha.html?upc=702825292812).

El Marco Geoestadístico (MG) es un producto que integra información vectorial, tablas de atributos y catálogos. Muestra la división geoestadística del territorio nacional en sucesivos niveles de desagregación. Esta división está dada por los llamados LÍMITES GEOESTADÍSTICOS, que pueden coincidir con los límites político-administrativos oficiales, los cuales tienen sustento legal; sin embargo, los que no cuentan con dicho sustento deben entenderse como límites provisionales, trazados sólo para realizar los operativos censales.

________
## Lectura de la información

Lectura de la información de la tabla del censo de población

Para cargar el archivo `nombre_ageb_urbana_05_cpv2020.csv` o puede ser 2010, se carga en un data frame. En la siguiente estructura podemos modificar la ruta donde se encuentra nuestro archivo.

```r
dir <- "ruta_del_directorio"
archivo <- "Nombre_del_archivo.csv"
dir_data <- file.path(dir, archivo)
```

Recuerda esto es para archivos separados por comas y tienen una terminación `*.csv`. El mismo proceso se realiza para el archivo vectorial y tiene terminación `*.shp`

In [28]:
dir <- "../../informacion/San_Luis/resultados_ageb_urbana_24_cpv2010/conjunto_de_datos"
archivo <- "resultados_ageb_urbana_24_cpv2010_1.csv"
dir_data <- file.path(dir, archivo)

Lectura del marco geoestadístico, cargar el archivo shp que tiene de nombre `a##.shp`, ## número de identidad

In [10]:
dir_shp <- "../../informacion/San_Luis/702825292812_s"
archivo_shp <- "AGEB_urb_2010_24.shp"
dir_shp <- file.path(dir_shp, archivo_shp)

En esta sección se cagaran las bibliotecas necesarias para el proceso

In [3]:
#02VulnerabilidadSocial

#carga de bibliotecas para la base de datos
library(tidyverse)

#cargar las bibliotecas para lectura Shapefile
library(sf)

#cargar las bibliotecas para la generación de mapas
library(leaflet)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Linking to GEOS 3.12.2, GDAL 3.9.3, PROJ 9.4.1; sf_use_s2() is TRUE

Crea la variable `db`en donde se carga la base de datos del archivo `*.csv`

In [29]:
db <- read.csv(dir_data, encoding = "UTF-8", stringsAsFactors = FALSE)
#head(db, 4)

Carga del archivo shapefile.

In [12]:
capa_ageb <- read_sf(dir_shp)

________

## Elección del año del censo de población y vivienda

Se le indica que censo de población se utliza para el analisis **2010** o **2020**, realiza las modificaciones necesarias para que la base de datos sean similares

In [30]:
# Solicitar al usuario que ingrese un valor
año <- readline(prompt = "¿Que año es el censo de población 2010 o 2020? (Escribe '2020' o '2010'): ")

# Validar la entrada del usuario y establecer el valor
if (año == "2020") {
    mensaje <- "Has elegido 2020."
} else if (año == "2010") {
    mensaje <- "Has elegido 2010."
    #Transforma de minúsculas a mayúsculas los nombres de las columnas de la base de datos
    colnames(db) <- toupper(colnames(db))
} else {
    mensaje <- "Opción no válida. Corre de nuevo la celda."
}

# Mostrar el mensaje
print(mensaje)

# El valor final de la variable "año"
print(paste("Censo de población usado:", año))

[1] "Has elegido 2010."
[1] "Censo de población usado: 2010"

In [31]:
head(db, 3)
str(db)

  ENTIDAD NOM_ENT         MUN NOM_MUN                             LOC
1 24      San Luis Potosí 0   Total de la entidad San Luis Potosí 0
2 24      San Luis Potosí 1   Ahualulco                           0
3 24      San Luis Potosí 1   Ahualulco                           1
  NOM_LOC                      AGEB MZA POBTOT  POBMAS  ⋯ VPH_SNBIEN VPH_RADIO
1 Total de la entidad          0000 0   2585518 1260366 ⋯ 24582      506720
2 Total del municipio          0000 0     18644 8775    ⋯ 241        3019
3 Total de la localidad urbana 0000 0      4492 2088    ⋯ 19         798
  VPH_TV VPH_REFRI VPH_LAVAD VPH_AUTOM VPH_PC VPH_TELEF VPH_CEL VPH_INTER
1 555492 493050    409181    280681    151052 235351    352662  103485
2 3420   2686      1721      1752      198    693       1720    82
3 925    768       569       453       137    380       568     63

'data.frame':	34086 obs. of  198 variables:
 $ ENTIDAD   : int  24 24 24 24 24 24 24 24 24 24 ...
 $ NOM_ENT   : chr  "San Luis Potosí" "San Luis Potosí" "San Luis Potosí" "San Luis Potosí" ...
 $ MUN       : int  0 1 1 1 1 1 1 1 1 1 ...
 $ NOM_MUN   : chr  "Total de la entidad San Luis Potosí" "Ahualulco" "Ahualulco" "Ahualulco" ...
 $ LOC       : int  0 0 1 1 1 1 1 1 1 1 ...
 $ NOM_LOC   : chr  "Total de la entidad" "Total del municipio" "Total de la localidad urbana" "Total AGEB urbana" ...
 $ AGEB      : chr  "0000" "0000" "0000" "0094" ...
 $ MZA       : int  0 0 0 0 1 3 4 5 6 7 ...
 $ POBTOT    : int  2585518 18644 4492 158 49 26 2 11 30 0 ...
 $ POBMAS    : chr  "1260366" "8775" "2088" "73" ...
 $ POBFEM    : chr  "1325152" "9869" "2404" "85" ...
 $ P_0A2     : chr  "144320" "1171" "306" "11" ...
 $ P_0A2_M   : chr  "73269" "596" "138" "6" ...
 $ P_0A2_F   : chr  "71051" "575" "168" "5" ...
 $ P_3YMAS   : chr  "2417759" "17441" "4180" "147" ...
 $ P_3YMAS_M : chr  "1175332" "8166" "1946" "67" ...
 $ P_3YMAS_F : chr  "1242427" "9275" "2234" "80" ...
 $ P_5YMAS   : chr  "2315022" "16669" "4000" "141" ...
 $ P_5YMAS_M : chr  "1123128" "7783" "1857" "65" ...
 $ P_5YMAS_F : chr  "1191894" "8886" "2143" "76" ...
 $ P_12YMAS  : chr  "1936607" "13647" "3319" "104" ...
 $ P_12YMAS_M: chr  "931632" "6255" "1502" "48" ...
 $ P_12YMAS_F: chr  "1004975" "7392" "1817" "56" ...
 $ P_15YMAS  : chr  "1775954" "12312" "2985" "94" ...
 $ P_15YMAS_M: chr  "850266" "5596" "1342" "43" ...
 $ P_15YMAS_F: chr  "925688" "6716" "1643" "51" ...
 $ P_18YMAS  : chr  "1608514" "10893" "2634" "80" ...
 $ P_18YMAS_M: chr  "765905" "4870" "1172" "37" ...
 $ P_18YMAS_F: chr  "842609" "6023" "1462" "43" ...
 $ P_3A5     : chr  "155207" "1170" "266" "9" ...
 $ P_3A5_M   : chr  "78750" "590" "133" "5" ...
 $ P_3A5_F   : chr  "76457" "580" "133" "4" ...
 $ P_6A11    : chr  "325945" "2624" "595" "34" ...
 $ P_6A11_M  : chr  "164950" "1321" "311" "14" ...
 $ P_6A11_F  : chr  "160995" "1303" "284" "20" ...
 $ P_8A14    : chr  "380802" "3125" "756" "33" ...
 $ P_8A14_M  : chr  "192844" "1533" "380" "14" ...
 $ P_8A14_F  : chr  "187958" "1592" "376" "19" ...
 $ P_12A14   : chr  "160653" "1335" "334" "10" ...
 $ P_12A14_M : chr  "81366" "659" "160" "5" ...
 $ P_12A14_F : chr  "79287" "676" "174" "5" ...
 $ P_15A17   : chr  "167440" "1419" "351" "14" ...
 $ P_15A17_M : chr  "84361" "726" "170" "6" ...
 $ P_15A17_F : chr  "83079" "693" "181" "8" ...
 $ P_18A24   : chr  "321953" "2295" "554" "23" ...
 $ P_18A24_M : chr  "156449" "983" "258" "10" ...
 $ P_18A24_F : chr  "165504" "1312" "296" "13" ...
 $ P_15A49_F : chr  "687834" "4857" "1223" "46" ...
 $ P_60YMAS  : chr  "257976" "2256" "459" "8" ...
 $ P_60YMAS_M: chr  "123962" "1063" "204" "5" ...
 $ P_60YMAS_F: chr  "134014" "1193" "255" "3" ...
 $ REL_H_M   : chr  "95.11" "88.91" "86.86" "85.88" ...
 $ POB0_14   : chr  "786125" "6300" "1501" "64" ...
 $ POB15_64  : chr  "1590938" "10604" "2629" "88" ...
 $ POB65_MAS : chr  "185016" "1708" "356" "6" ...
 $ PROM_HNV  : chr  "2.59" "3.23" "2.76" "2.7" ...
 $ PNACENT   : chr  "2282773" "17818" "4156" "150" ...
 $ PNACENT_M : chr  "1115901" "8393" "1921" "67" ...
 $ PNACENT_F : chr  "1166872" "9425" "2235" "83" ...
 $ PNACOE    : chr  "260447" "615" "255" "7" ...
 $ PNACOE_M  : chr  "123058" "272" "122" "5" ...
 $ PNACOE_F  : chr  "137389" "343" "133" "*" ...
 $ PRES2005  : chr  "2218398" "16125" "3765" "136" ...
 $ PRES2005_M: chr  "1067245" "7420" "1716" "61" ...
 $ PRES2005_F: chr  "1151153" "8705" "2049" "75" ...
 $ PRESOE05  : chr  "57368" "157" "103" "0" ...
 $ PRESOE05_M: chr  "28733" "77" "54" "0" ...
 $ PRESOE05_F: chr  "28635" "80" "49" "0" ...
 $ P3YM_HLI  : chr  "256468" "14" "8" "*" ...
 $ P3YM_HLI_M: chr  "129400" "6" "6" "*" ...
 $ P3YM_HLI_F: chr  "127068" "8" "*" "0" ...
 $ P3HLINHE  : chr  "21870" "0" "0" "0" ...
 $ P3HLINHE_M: chr  "8312" "0" "0" "0" ...
 $ P3HLINHE_F: chr  "13558" "0" "0" "0" ...
 $ P3HLI_HE  : chr  "229288" "4" "4" "0" ...
 $ P3HLI_HE_M: chr  "118432" "3" "3" "0" ...
 $ P3HLI_HE_F: chr  "110856" "*" "*" "0" ...
 $ P5_HLI    : chr  "248196" "13" "8" "*" ...
 $ P5_HLI_NHE: chr  "19439" "0" "0" "0" ...
 $ P5_HLI_HE : chr  "223605" "4" "4" "0" ...
 $ PHOG_IND  : chr  "356230" "50" "32" "5" ...
 $ PCON_LIM  : chr  "117700" "1294" "296" "8" ...
 $ PCLIM_MOT : chr  "63758" "800" "199" "3" ...
 $ PCLIM_VIS : chr  "33856" "345" "74" "*" ...
 $ PCLIM_LENG: chr  "11390" "72" "17" "*" ...
 $ PCLIM_AUD : chr  "15317" "148" "27" "0" ...
 $ PCLIM_MOT2: chr  "6973" "41" "8" "0" ...
 $ PCLIM_MEN : chr  "6633" "43" "15" "0" ...
 $ PCLIM_MEN2: chr  "12157" "121" "26" "*" ...
 $ PSIN_LIM  : chr  "2432657" "17249" "4187" "150" ...
 $ P3A5_NOA  : chr  "53414" "470" "99" "*" ...
 $ P3A5_NOA_M: chr  "27407" "234" "46" "0" ...
 $ P3A5_NOA_F: chr  "26007" "236" "53" "*" ...
 $ P6A11_NOA : chr  "6823" "52" "10" "*" ...
 $ P6A11_NOAM: chr  "3692" "27" "3" "*" ...
 $ P6A11_NOAF: chr  "3131" "25" "7" "0" ...
 $ P12A14NOA : chr  "10423" "110" "20" "*" ...
 $ P12A14NOAM: chr  "5642" "52" "10" "0" ...
 $ P12A14NOAF: chr  "4781" "58" "10" "*" ...
  [list output truncated]

In [33]:
############# Selección de los AGEBS ##################
#Hacemos un filtro solo para los valores de AGEB urbana
db <- db %>% filter(NOM_LOC== "Total AGEB urbana")

In [34]:
# Cambio de caracteres para que los asteriscos queden como NA
db[db == "*"] <- ""

In [38]:
db <- db %>% mutate_at(vars(c(10:ncol(db))), as.integer)
# función para cambiar los valores de doble a entero
#db <- db %>% mutate_at(vars(c(9:ncol(db))), as.integer)

In [39]:
head(db, 4)

  ENTIDAD NOM_ENT         MUN NOM_MUN   LOC NOM_LOC           AGEB MZA POBTOT
1 24      San Luis Potosí 1   Ahualulco 1   Total AGEB urbana 0094 0    158
2 24      San Luis Potosí 1   Ahualulco 1   Total AGEB urbana 0107 0   1823
3 24      San Luis Potosí 1   Ahualulco 1   Total AGEB urbana 0111 0   2068
4 24      San Luis Potosí 1   Ahualulco 1   Total AGEB urbana 0126 0     79
  POBMAS ⋯ VPH_SNBIEN VPH_RADIO VPH_TV VPH_REFRI VPH_LAVAD VPH_AUTOM VPH_PC
1  73    ⋯  3          20        27     20        11        12        0
2 842    ⋯ NA         330       386    329       258       205       75
3 970    ⋯ 13         373       427    361       262       191       55
4  38    ⋯  0          13        13     13         8        10       NA
  VPH_TELEF VPH_CEL VPH_INTER
1   4        17     NA
2 167       261     30
3 196       223     29
4   3         9      0

In [40]:
db <- db %>%
        mutate(
          ENTIDAD = str_pad(ENTIDAD, width = 2, side = "left", pad = "0"),
          MUN = str_pad(MUN, width = 3, side = "left", pad = "0"),
          LOC = str_pad(LOC, width = 4, side = "left", pad = "0"),
          CVEGEO = paste0(ENTIDAD, MUN, LOC, AGEB)  # Generar CVEGEO corregido
        )

In [41]:
head(db, 10)

   ENTIDAD NOM_ENT         MUN NOM_MUN   LOC  NOM_LOC           AGEB MZA POBTOT
1  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0094 0    158
2  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0107 0   1823
3  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0111 0   2068
4  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0126 0     79
5  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0130 0     72
6  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0145 0     31
7  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 015A 0     38
8  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0164 0     56
9  24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0179 0     28
10 24      San Luis Potosí 001 Ahualulco 0001 Total AGEB urbana 0183 0     99
   POBMAS ⋯ VPH_RADIO VPH_TV VPH_REFRI VPH_LAVAD VPH_AUTOM VPH_PC VPH_TELEF
1   73    ⋯  20        27     20        11        12        0       4
2  842    ⋯ 330       386    329       258       205       75     167
3  970    ⋯ 373       427    361       262       191       55     196
4   38    ⋯  13        13     13         8        10       NA       3
5   34    ⋯  13        13     12         8        10       NA       5
6   13    ⋯   3         5      4         3         3       NA       0
7   16    ⋯   8         8      6         5         4       NA       3
8   27    ⋯  11        11      9         7         4        0      NA
9   11    ⋯   5         6      3         0         3       NA       0
10  44    ⋯  14        20      8         6         5        0       0
   VPH_CEL VPH_INTER CVEGEO
1   17     NA        2400100010094
2  261     30        2400100010107
3  223     29        2400100010111
4    9      0        2400100010126
5   11     NA        2400100010130
6    3      0        2400100010145
7    5     NA        240010001015A
8    9      0        2400100010164
9    4     NA        2400100010179
10  18      0        2400100010183

In [42]:
Ent <- db %>% filter(NOM_LOC== "Total de la entidad")

In [ ]:
capa_ageb <- read_sf(dir_shp)
capa_ageb <- st_transform(capa_ageb, "+proj=longlat +datum=WGS84 +no_defs")

In [ ]:
capa_ageb$area_km2 <- st_area(capa_ageb) / 10^6
#convertir el tipo de columna
capa_ageb$area_km2 <- as.numeric(capa_ageb$area_km2)

In [ ]:
# Coordenadas del centro de la zona de interes, cambiar
latitud <- 22.155152
longitud <- -100.974473
zoom <- 11  # Nivel de zoom deseado

In [ ]:

# Crear una paleta de colores para representar la población de las AGEB
pal <- colorQuantile("Blues", domain = capa_ageb$area_km2, n=5)

# Crear un mapa interactivo con Leaflet
mapa <- leaflet(capa_ageb) %>%
  addTiles() %>%
  addPolygons(
    fillColor =  ~pal(area_km2),
    fillOpacity = 0.5,
    color = "black",
    weight = 1,
    popup = ~paste("Área:", round(area_km2,3), "km²"), # Muestra los datos al hacer clic en un polígono
    label = ~CVEGEO # Indica el nombre al poner el cursor
  ) %>%
  addLegend(
    pal = pal,
    values = ~area_km2,
    title = "Área en kilómetros cuadrados",
    opacity = 1,
    position = "bottomright"  # Cambia la posición de la leyenda si es necesario
  ) %>%
  setView(lng = longitud, lat = latitud, zoom = zoom)  # Establece el centro y el nivel de zoom

# Establecer la altura del mapa en 600px
mapa <- htmlwidgets::onRender(mapa, '
  function(el, x) {
    $(el).css("height", "800px");
  }
')

# Agregar un título utilizando etiquetas HTML en la leyenda
mapa <- mapa %>% 
  addControl(
    html = '<div style="text-align: center; background-color: #fff; padding: 10px;"><h3>Mapa de las AGEB de San Luis</h3></div>',
    position = "topright"  # Cambia la posición del título si es necesario
  )

# Mostrar el mapa interactivo
mapa

In [ ]:
# Unir las dos tablas
capa_ageb <- capa_ageb %>%
  left_join(db, by="CVEGEO")

In [ ]:
# Filtrar las filas que no tienen coincidencia en db_T y el shape file del AGEB
# se deja solo las coincidencias de la clave CVEGEO
capa_ageb <- capa_ageb %>%
  filter(NOM_LOC== "Total AGEB urbana")

In [ ]:
# Crear una paleta de colores para representar la población de las AGEB
pal <- colorQuantile("YlOrRd", domain = capa_ageb$POBTOT, n=5)

# Crear un mapa interactivo con Leaflet
mapa <- leaflet(capa_ageb) %>%
  addTiles() %>%
  addPolygons(
    fillColor =  ~pal(POBTOT),
    fillOpacity = 0.5,
    color = "black",
    weight = 1,
    popup = ~paste("Población: ", POBTOT, " habitantes", "<br>", "AGEB: ", AGEB, "<br>", "Municipio: ", NOM_MUN),
    label = ~NOM_MUN
  ) %>%
  addLegend(
    pal = pal,
    values = ~POBTOT,
    title = "Densidad de Población",
    opacity = 1,
    position = "bottomright"
  ) %>%
  setView(lng = longitud, lat = latitud, zoom = zoom)  # Establece el centro y el nivel de zoom

# Establecer la altura del mapa en 600px
mapa <- htmlwidgets::onRender(mapa, '
  function(el, x) {
    $(el).css("height", "800px");
  }
')


# Agregar un título utilizando etiquetas HTML en la leyenda
mapa <- mapa %>% 
  addControl(
    html = '<div style="text-align: center; background-color: #fff; padding: 10px;"><h3>Mapa de población por AGEB de Jalisco</h3></div>',
    position = "topright"
  )

# Mostrar el mapa interactivo
mapa

Función para escalar los indices para la evaluación de la vulnerabilidad socioeconomica, utilizando el metodo de normalización mínimo-máximo

In [ ]:
nor_mm <- function(x) {
  rng <- range(x, na.rm = TRUE, finite = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}

In [ ]:
?na.rm